#!/usr/bin/env python3
import os
import sys

if not sys.argv[1:]:
    print("Usage: {} <imgpath1> <imgpath2> ...".format(sys.argv[0]))
    sys.exit(1)

TEMPLATE = """
\\begin{figure}[htb]
\t\\centering
\t\\includegraphics[width=0.5\\textwidth]{%s}
\t\\caption{\t}
\t\\label{fig:%s}
\\end{figure}
"""

for filepath in sys.argv[1:]:
    full_dirname = os.path.dirname(filepath)
    dirname = os.path.split(full_dirname)[-1]
    basename = os.path.basename(filepath)
    figpath = os.path.join("figures", dirname, basename)
    label = os.path.splitext(basename)[0]

    figtex = TEMPLATE % (figpath, label)
    print(figtex)
